controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#home_index:
    #path: /home
    #contrller: App\Controller\IndexController::home 
    #Requirements:
        #name: '\d+'